--- Makefile
+++ Makefile
@@ -21,6 +21,9 @@
 tests/test_usable_size: tests/test_usable_size.c mybuddy.h
	$(CC) $(CFLAGS) $< -o $@

+tests/test_multithread_stress: tests/test_multithread_stress.c mybuddy.h
+	$(CC) $(CFLAGS) $< -o $@
+
 test: $(TESTS)
	@echo "Running basic tests..."
	@./tests/test_basic
@@ -34,6 +37,8 @@
	@./tests/test_string_view
	@echo "Running usable size tests..."
	@./tests/test_usable_size
+	@echo "Running multi-thread stress tests..."
+	@./tests/test_multithread_stress
	@echo "All tests passed successfully!"

 clean:
